server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/module_accounts
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"

build:
  version: "1.0"

cards:
  message: "Welcome to NguyenHoangThaiTuan cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
