server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/module_accounts
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
