spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:D:/config"
        git:
          uri: "https://github.com/nguyenhoangthaituandev/microservice-config.git"
          default-label: main
          timeout: 10000
          clone-on-start: true
          force-pull: true

encrypt:
  key: "AAF3504"

server:
  port: 8071
