server:
  port: 8090

spring:
  application:
    name: loans

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/module_accounts
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true



