spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to NguyenHoangThaiTuan accounts related prod APIs "
  contactDetails:
    name: "John Doe - product"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345