version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_accounts
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  accounts:
    build: ./accounts
    container_name: accounts
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASS: mypass
      DB_NAME: mydb
    depends_on:
      - postgres

  loans:
    build: ./loans
    container_name: loans
    ports:
      - "8090:8090"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASS: mypass
      DB_NAME: mydb
    depends_on:
      - postgres

  cards:
    build: ./cards
    container_name: cards
    ports:
      - "9000:9000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASS: mypass
      DB_NAME: mydb
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin_data:
